// GENERATED by scripts/refresh-data.ts on 2026-08-31 — do not hand-edit.
// Monthly-verified menswear pricing intel for the directory's key retailers.
// Empty this run (search quota exhausted); the monthly workflow repopulates it.
export const PRICE_BRIEF_DATE = "2026-08-31";
export const PRICE_BRIEF = "";
