// GENERATED by scripts/refresh-data.ts — do not hand-edit.
// Monthly-verified menswear pricing intel for the directory's key retailers.
// Empty until the first refresh run populates it.
export const PRICE_BRIEF_DATE = "";
export const PRICE_BRIEF = "";
