// GENERATED by scripts/research-stores.ts on 2026-08-31 — do not hand-edit.
// Deep per-store intelligence from live web research: the brands each
// store actually carries, real price points, and the insider detail that
// makes it worth the drive.
export interface StoreIntel {
  brands: string[];
  pricePoints: string[];
  insiderTake: string;
  researchedAt: string;
}

export const STORE_INTEL: Record<string, StoreIntel> = {
  "tom-james": {
    "brands": [
      "Tom James (house label)",
      "Oxxford Clothes",
      "Holland & Sherry",
      "H. Freeman",
      "Corbin",
      "Coppley",
      "Gitman Bros",
      "Individualized Shirts",
      "Loro Piana (fabric)",
      "Scabal (fabric)"
    ],
    "pricePoints": [
      "made-to-measure suit: from ~$700",
      "made-to-measure suit: typical range $1,100-$2,500",
      "made-to-measure suit: realistic all-in cost incl. alterations ~$1,300",
      "made-to-measure suit (top-tier fabric/mill, e.g. Oxxford): $2,000+"
    ],
    "insiderTake": "Outcome hinges on your assigned clothier, not the brand; Houston clients specifically praise rep Dusty Schroeder—ask by name and get fabric-tier/alteration costs itemized upfront.",
    "researchedAt": "2026-08-31"
  },
  "norton-ditto": {
    "brands": [
      "Oxxford Clothes",
      "Hickey Freeman",
      "Canali",
      "Ravazzolo",
      "H. Freeman & Sons",
      "Peter Millar",
      "Robert Graham",
      "Robert Talbot",
      "Zanella",
      "Southern Tide"
    ],
    "pricePoints": [
      "suit (off-the-rack/designer): from $995, most $1,600+"
    ],
    "insiderTake": "Complimentary in-house tailoring on every purchase; their real strength is true bespoke (Oxxford) and Italian MTM (Ravazzolo/Canali), not the trendier sportswear racks.",
    "researchedAt": "2026-08-31"
  },
  "hamilton-shirts": {
    "brands": [
      "Hamilton (house label)",
      "Hamilton 1883",
      "Hamilton Americana",
      "Lyle Lovett for Hamilton",
      "Thomas Mason (exclusive US bespoke fabric partner)",
      "Hiltl Pants",
      "AG Denim",
      "Alan Paine",
      "Bigi of Milan"
    ],
    "pricePoints": [
      "bespoke shirt (5-shirt minimum first order): $295-$395",
      "made-to-measure shirt: $290-$335",
      "standard/ready-to-wear dress shirt: from $225",
      "tuxedo shirt: $245",
      "women's shirts (Classic/Boyfriend/Tunic): $275-$345",
      "custom shirt in Thomas Mason fabrics: $195-$595"
    ],
    "insiderTake": "Collars/cuffs use fabric lining, not glued fusing—one of only three shirtmakers worldwide to do this. Bespoke requires a 5-shirt minimum first order; MTM is faster and cheaper if you just want a great fit.",
    "researchedAt": "2026-08-31"
  },
  "q-clothier": {
    "brands": [
      "Q Clothier"
    ],
    "pricePoints": [],
    "insiderTake": "The Kirby Dr shop sits inside Arrive with an in-store whiskey bar and is physically connected to sister casual shop Rye51 — linger there during your consultation and fittings.",
    "researchedAt": "2026-08-31"
  },
  "kuffs-houston": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "It's essentially a one-woman operation (Kathryn Hinte, clothier since 1993) doing true home/office fittings by appointment — no walk-in showroom, so book ahead rather than dropping by.",
    "researchedAt": "2026-08-31"
  },
  "lucho": {
    "brands": [
      "Lucho"
    ],
    "pricePoints": [],
    "insiderTake": "Ask about their fast ~7-day custom suit turnaround and built-in alterations service — Lucho's real strength is made-to-measure fit and personal tailor relationships, not off-the-rack shopping.",
    "researchedAt": "2026-08-31"
  },
  "bill-walker-clothier": {
    "brands": [
      "Hickey Freeman",
      "Southwick",
      "John Cooper (Savile Row)",
      "Robert Talbott",
      "Vineyard Vines",
      "Tommy Bahama",
      "Peter Millar",
      "Bills Khakis",
      "Polo Ralph Lauren",
      "34 Heritage"
    ],
    "pricePoints": [],
    "insiderTake": "Ask for Philip Linkous or Shelley Walker Caldwell—longtime senior staff who personally run fittings; the shop's real strength is custom tailoring/fabric sourcing (e.g. Scabal), not its casual racks.",
    "researchedAt": "2026-08-31"
  },
  "blu-fine-menswear": {
    "brands": [
      "BLU Fine Menswear (house label)",
      "WESTERN BLU",
      "Zegna",
      "Scabal",
      "Dormeuil",
      "Holland & Sherry",
      "Loro Piana",
      "Republic Boot Co."
    ],
    "pricePoints": [
      "custom (made-to-measure) suit: from $1,300",
      "full bespoke suit: from $3,500",
      "dress shirt (100% Egyptian cotton): $155",
      "signature three-harness Prince of Wales trouser: $265",
      "wedding consultation call: free (15 min)"
    ],
    "insiderTake": "Ask for owner Steve Springer directly; he personally runs every consultation. For faster, no-wait pieces skip bespoke and ask about WESTERN BLU, their in-stock ready-to-wear line made with Republic Boot Co.",
    "researchedAt": "2026-08-31"
  },
  "indochino-galleria": {
    "brands": [
      "Indochino"
    ],
    "pricePoints": [
      "made-to-measure suit: from $399"
    ],
    "insiderTake": "Ask about the Perfect Fit Promise: if your first suit doesn't fit right, they remake it free — trust the in-store stylist measurement over any self-measure online order.",
    "researchedAt": "2026-08-31"
  },
  "bzach-clothier": {
    "brands": [
      "Bzach"
    ],
    "pricePoints": [],
    "insiderTake": "Ask for Balu by name — reviews across all Bzach locations consistently credit him, not just 'the store,' for fit, fabric picks, and fast turnaround.",
    "researchedAt": "2026-08-31"
  },
  "festari-for-men": {
    "brands": [
      "Festari (in-house label)",
      "Ermenegildo Zegna",
      "Loro Piana",
      "Scabal",
      "Holland & Sherry",
      "Vitale Barberis Canonico",
      "Reda",
      "Drago",
      "Coppley"
    ],
    "pricePoints": [
      "ready-to-wear suit: $898",
      "made-to-measure/custom suit: $1,100-$10,000",
      "Zegna linen ready-to-wear trousers: $998"
    ],
    "insiderTake": "Ask for Rudy Festari himself—he still personally consults and, for time-strapped clients, will do fittings at your home or office rather than the Post Oak store.",
    "researchedAt": "2026-08-31"
  },
  "m-penner": {
    "brands": [
      "Ermenegildo Zegna",
      "Canali",
      "Isaia",
      "Kiton",
      "Samuelsohn",
      "Brunello Cucinelli",
      "Stenstroms",
      "Santoni",
      "Magnanni",
      "Bontoni"
    ],
    "pricePoints": [],
    "insiderTake": "Owner Murry Penner personally curates the shoe program with specialist Wallace; made-to-measure fittings feel like an event, and Karen Penner still bakes brownies for Saturday regulars.",
    "researchedAt": "2026-08-31"
  },
  "neiman-marcus-galleria": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "saks-galleria": {
    "brands": [
      "Louis Vuitton",
      "Gucci",
      "Christian Louboutin",
      "Creed (House of Creed)",
      "Zegna",
      "Thom Browne",
      "Isaia",
      "Brunello Cucinelli",
      "Canali",
      "DSquared2"
    ],
    "pricePoints": [],
    "insiderTake": "Skip the racks and book the Fifth Avenue Club's private men's suites for made-to-order suits and off-site fittings via Saks' dedicated Mercedes Sprinter styling van.",
    "researchedAt": "2026-08-31"
  },
  "nordstrom-galleria": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "zegna-houston": {
    "brands": [
      "ZEGNA (Ermenegildo Zegna house label)",
      "Oasi Cashmere (in-house luxury cashmere collection)",
      "Triple Stitch (signature footwear line)",
      "XXX (Zegna streetwear/tailoring capsule)"
    ],
    "pricePoints": [
      "Triple Stitch sneakers: $895-$1,290",
      "Oasi Cashmere overshirt: $3,590",
      "ready-to-wear suit (Centoventimila wool): from $7,150",
      "made-to-measure/RTW suit range: $1,750-$7,150",
      "Oasi Cashmere cardigan: $2,750",
      "cashmere scarf: $630"
    ],
    "insiderTake": "Ask for the Su Misura appointment and the invite-only Vellus Aureum fabric event—Zegna is strongest at made-to-measure tailoring, not the streetwear/sneaker capsules it also stocks.",
    "researchedAt": "2026-08-31"
  },
  "brioni-river-oaks": {
    "brands": [
      "Brioni"
    ],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "brunello-cucinelli-river-oaks": {
    "brands": [
      "Brunello Cucinelli"
    ],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "hermes-river-oaks": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "louis-vuitton-mens-galleria": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "the-black-tux-galleria": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "als-formal-wear": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "dxl-big-tall": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "sid-mashburn": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "suitsupply-river-oaks-district": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "rye-51": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "premium-goods": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "buck-mason": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "marine-layer-rice-village": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "manready-mercantile": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "lucchese": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "cavenders": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "tecovas-rice-village": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "republic-boot-co": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "the-hat-store": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "pinto-ranch": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "allen-edmonds-houston": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "johnston-murphy-galleria": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "qc-tailors": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "warby-parker-rice-village": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "eye-elegance": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "kuhl-linscomb": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  },
  "zadok-jewelers": {
    "brands": [],
    "pricePoints": [],
    "insiderTake": "",
    "researchedAt": "2026-08-31"
  }
};
