// GENERATED by scripts/refresh-data.ts on 2026-08-31 — do not hand-edit.
// Per-store freshness from live web search: operating status + one current note.
export interface StoreFreshness {
  status: "open" | "closed" | "unclear";
  note: string;
  confidence: "high" | "low";
  checkedAt: string;
}

export const STORE_FRESHNESS: Record<string, StoreFreshness> = {
  "tom-james": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "norton-ditto": {
    "status": "open",
    "note": "Vicuña wool Custom Show in-store featuring rare wool sport coats/suits at their West Alabama at Kirby location.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "hamilton-shirts": {
    "status": "open",
    "note": "",
    "confidence": "low",
    "checkedAt": "2026-08-31"
  },
  "q-clothier": {
    "status": "open",
    "note": "Located at West Ave (2800 Kirby Dr, Ste B124); shares space with sister boutique Rye 51 for casual menswear.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "kuffs-houston": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "lucho": {
    "status": "unclear",
    "note": "",
    "confidence": "low",
    "checkedAt": "2026-08-31"
  },
  "bill-walker-clothier": {
    "status": "open",
    "note": "Located at 1737 Post Oak Blvd, Houston; known for in-house tailoring and custom suits/tuxedos.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "blu-fine-menswear": {
    "status": "unclear",
    "note": "",
    "confidence": "low",
    "checkedAt": "2026-08-31"
  },
  "indochino-galleria": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "bzach-clothier": {
    "status": "open",
    "note": "Two Houston storefronts (3733 Westheimer Rd & 6811 SW Freeway) plus appointment booking; walk-ins also welcome.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "festari-for-men": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "m-penner": {
    "status": "open",
    "note": "",
    "confidence": "low",
    "checkedAt": "2026-08-31"
  },
  "neiman-marcus-galleria": {
    "status": "open",
    "note": "Offers in-store shopping by appointment and curbside pickup (dial 713-265-7783 on arrival).",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "saks-galleria": {
    "status": "open",
    "note": "Store features 51fifteen restaurant on-site for refreshments and light bites.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "nordstrom-galleria": {
    "status": "open",
    "note": "",
    "confidence": "low",
    "checkedAt": "2026-08-31"
  },
  "zegna-houston": {
    "status": "open",
    "note": "Zegna Boutique at Houston Galleria; Mon-Sat 11-7, Sun 12-6; boutique delivery & returns available.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "brioni-river-oaks": {
    "status": "open",
    "note": "Brioni hosted an in-store trunk show at its River Oaks District location (4444 Westheimer Rd, Suite C115) in May 2025.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "brunello-cucinelli-river-oaks": {
    "status": "open",
    "note": "Undergoing $1.8M expansion to 4,750+ sq ft at 4444 Westheimer Rd, Suite F155, starting April 2026 (completion Oct 2026).",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "hermes-river-oaks": {
    "status": "open",
    "note": "Store had a temporary closure May 22–29 (reopened May 30); located at 4444 Westheimer Rd, Ste A-160, River Oaks District.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "louis-vuitton-mens-galleria": {
    "status": "open",
    "note": "Located at 5015 Westheimer (Galleria 1), Suite A2414; offers on-site hot stamping and personalization services.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "the-black-tux-galleria": {
    "status": "open",
    "note": "Located inside Nordstrom, 1st Floor Men's Clothing dept at Galleria; book appointments for suit/tux fittings.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "als-formal-wear": {
    "status": "closed",
    "note": "All Al's Formal Wear locations abruptly shut down permanently in August 2023, leaving customers without tuxedos or refunds.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "dxl-big-tall": {
    "status": "open",
    "note": "Store offers curbside pickup; official listing shows active hours (Mon-Sat 10am-7pm, Sun 12-6pm)",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "sid-mashburn": {
    "status": "open",
    "note": "Store doing light renovations; doors temporarily closed through Mon, July 28 at 10am (alterations/pickup via Sid Shop Manager).",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "suitsupply-river-oaks-district": {
    "status": "open",
    "note": "Store is actually at West Ave shopping center (2601 Westheimer #220), not inside River Oaks District mall, though both sit in Houston's Upper Kirby/River Oaks area.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "rye-51": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "premium-goods": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "buck-mason": {
    "status": "open",
    "note": "Located at 906 Westheimer Rd in Montrose Collective; open Mon-Sat 11am-7pm, Sun 11am-6pm.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "marine-layer-rice-village": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "manready-mercantile": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "lucchese": {
    "status": "unclear",
    "note": "",
    "confidence": "low",
    "checkedAt": "2026-08-31"
  },
  "cavenders": {
    "status": "open",
    "note": "New Copperfield store (6757 Hwy 6 N) just opened; new Katy Mills-area location opening May 1, 2026",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "tecovas-rice-village": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "republic-boot-co": {
    "status": "open",
    "note": "Also operates a second location, 'Republic Wine Castle,' in Johnson City, TX alongside the Houston Heights shop.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "the-hat-store": {
    "status": "unclear",
    "note": "",
    "confidence": "low",
    "checkedAt": "2026-08-31"
  },
  "pinto-ranch": {
    "status": "open",
    "note": "Store briefly closed abruptly in June 2024 but reopened under new management; still active in 2025 (sponsored 2025 NFR event).",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "allen-edmonds-houston": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "johnston-murphy-galleria": {
    "status": "open",
    "note": "Located Level 1 near Galleria Financial Center, 5061 Westheimer Rd; hours vary Mon–Sun (e.g., Sun 12–7PM).",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "qc-tailors": {
    "status": "open",
    "note": "Located at 3801 Kirby Dr Suite 100 in Upper Kirby; has operated on Kirby Dr since 1998.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "warby-parker-rice-village": {
    "status": "open",
    "note": "Currently offering 15% off when you buy 2+ prescription eyewear pairs (optical/optical, optical/sun, or sun/sun).",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "eye-elegance": {
    "status": "open",
    "note": "Two Houston locations (Post Oak Blvd & Montrose/Westheimer Rd); ran an End of Season Sale Sep 15–Oct 11, 2025 at Montrose Collective store",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "kuhl-linscomb": {
    "status": "unclear",
    "note": "",
    "confidence": "low",
    "checkedAt": "2026-08-31"
  },
  "zadok-jewelers": {
    "status": "open",
    "note": "Expanded in 2021 to a 28,000 sq ft flagship on Post Oak Blvd; family-run since 1976",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  }
};
