// GENERATED by scripts/research-social.ts on 2026-08-31, do not hand-edit.
// Official public social profile links per store. Links only, by design:
// we point people at the source, we never copy its content.
export interface StoreSocial {
  instagram?: string;
  facebook?: string;
  active?: boolean;
}

export const STORE_SOCIAL: Record<string, StoreSocial> = {
  "norton-ditto": {
    "instagram": "nortonditto",
    "facebook": "https://www.facebook.com/norton.ditto",
    "active": true
  },
  "hamilton-shirts": {
    "instagram": "hamiltonshirts",
    "facebook": "https://www.facebook.com/HamiltonShirts/",
    "active": true
  },
  "kuffs-houston": {
    "instagram": "kuffshouston",
    "active": false
  },
  "blu-fine-menswear": {
    "instagram": "blufinemenswear",
    "facebook": "https://www.facebook.com/Blufinemenswear/",
    "active": true
  },
  "indochino-galleria": {
    "instagram": "indochino",
    "facebook": "https://www.facebook.com/indochino",
    "active": true
  },
  "m-penner": {
    "instagram": "mpennerhouston",
    "facebook": "https://www.facebook.com/mpennerhouston/",
    "active": true
  },
  "nordstrom-galleria": {
    "facebook": "https://www.facebook.com/NordstromHoustonGalleria/",
    "active": true
  },
  "brioni-river-oaks": {
    "instagram": "brioni_official",
    "active": false
  },
  "tom-james": {
    "facebook": "https://www.facebook.com/TomJameshouston/",
    "active": false
  },
  "bill-walker-clothier": {
    "instagram": "billwalkerclothier",
    "active": true
  },
  "bzach-clothier": {
    "instagram": "bzachhouston",
    "facebook": "https://www.facebook.com/bzachhouston/",
    "active": true
  },
  "festari-for-men": {
    "instagram": "festariformen",
    "facebook": "https://www.facebook.com/festariformen/",
    "active": false
  },
  "neiman-marcus-galleria": {
    "instagram": "neimanmarcushouston",
    "active": true
  },
  "louis-vuitton-mens-galleria": {
    "instagram": "louisvuitton",
    "facebook": "https://www.facebook.com/LouisVuitton",
    "active": true
  },
  "the-black-tux-galleria": {
    "instagram": "theblacktux",
    "facebook": "https://www.facebook.com/theblacktux",
    "active": true
  },
  "dxl-big-tall": {
    "facebook": "https://www.facebook.com/DXLHoustonTX5393WestheimerRoad/",
    "active": true
  },
  "sid-mashburn": {
    "instagram": "sidmashburn",
    "facebook": "https://www.facebook.com/mashburnhouston/",
    "active": true
  },
  "suitsupply-river-oaks-district": {
    "facebook": "https://www.facebook.com/SuitsupplyHouston/",
    "active": true
  },
  "rye-51": {
    "instagram": "rye51_houston",
    "facebook": "https://www.facebook.com/RYE51Houston/",
    "active": false
  },
  "premium-goods": {
    "instagram": "premiumgoodshtx",
    "facebook": "https://www.facebook.com/premiumgoodshtx/",
    "active": true
  },
  "manready-mercantile": {
    "instagram": "manreadymerc",
    "facebook": "https://www.facebook.com/manreadymerc/",
    "active": true
  },
  "tecovas-rice-village": {
    "instagram": "tecovas",
    "facebook": "https://www.facebook.com/Tecovashouston/",
    "active": true
  },
  "pinto-ranch": {
    "instagram": "pintoranch",
    "facebook": "https://www.facebook.com/pintoranch/",
    "active": true
  },
  "allen-edmonds-houston": {
    "instagram": "allenedmonds",
    "active": true
  },
  "qc-tailors": {
    "instagram": "qualitycustomtailors",
    "facebook": "https://www.facebook.com/p/Quality-Custom-Tailors-100054619051765/",
    "active": false
  },
  "warby-parker-rice-village": {
    "instagram": "warbyparker",
    "facebook": "https://www.facebook.com/warbyparker",
    "active": true
  },
  "kuhl-linscomb": {
    "instagram": "kuhllinscomb",
    "facebook": "https://www.facebook.com/kuhl.linscomb/",
    "active": true
  },
  "zadok-jewelers": {
    "instagram": "zadokjewelers",
    "facebook": "https://www.facebook.com/zadokjewelers/",
    "active": true
  },
  "hermes-river-oaks": {
    "instagram": "hermes",
    "facebook": "https://www.facebook.com/Hermes",
    "active": true
  },
  "als-formal-wear": {
    "instagram": "alsformalwear",
    "facebook": "https://www.facebook.com/alsformalwear/",
    "active": true
  },
  "marine-layer-rice-village": {
    "instagram": "marinelayer",
    "facebook": "https://www.facebook.com/marinelayer/",
    "active": true
  },
  "cavenders": {
    "instagram": "cavenders",
    "active": true
  },
  "republic-boot-co": {
    "instagram": "republicboot1836",
    "facebook": "https://www.facebook.com/RepublicBootCo/",
    "active": true
  },
  "johnston-murphy-galleria": {
    "instagram": "johnstonmurphy",
    "facebook": "https://www.facebook.com/johnstonmurphy",
    "active": true
  }
};
