// GENERATED by scripts/research-social.ts on 2026-08-31, do not hand-edit.
// Official public social profile links per store. Links only, by design:
// we point people at the source, we never copy its content.
export interface StoreSocial {
  instagram?: string;
  facebook?: string;
  active?: boolean;
}

export const STORE_SOCIAL: Record<string, StoreSocial> = {
  "norton-ditto": {
    "instagram": "nortonditto",
    "facebook": "https://www.facebook.com/norton.ditto",
    "active": true
  },
  "hamilton-shirts": {
    "instagram": "hamiltonshirts",
    "facebook": "https://www.facebook.com/HamiltonShirts/",
    "active": true
  },
  "kuffs-houston": {
    "instagram": "kuffshouston",
    "active": false
  },
  "blu-fine-menswear": {
    "instagram": "blufinemenswear",
    "facebook": "https://www.facebook.com/Blufinemenswear/",
    "active": true
  },
  "indochino-galleria": {
    "instagram": "indochino",
    "facebook": "https://www.facebook.com/indochino",
    "active": true
  },
  "m-penner": {
    "instagram": "mpennerhouston",
    "facebook": "https://www.facebook.com/mpennerhouston/",
    "active": true
  },
  "nordstrom-galleria": {
    "facebook": "https://www.facebook.com/NordstromHoustonGalleria/",
    "active": true
  },
  "brioni-river-oaks": {
    "instagram": "brioni_official",
    "active": false
  }
};
