// GENERATED by scripts/research-stores.ts — do not hand-edit.
// Deep per-store intelligence from live web research: the brands each
// store actually carries, real price points, and the insider detail that
// makes it worth the drive. Empty until the first research run.
export interface StoreIntel {
  brands: string[];
  pricePoints: string[];
  insiderTake: string;
  researchedAt: string;
}

export const STORE_INTEL: Record<string, StoreIntel> = {};
