// GENERATED by scripts/refresh-data.ts on 2026-08-31 — do not hand-edit.
// Per-store freshness from live web search: operating status + one current note.
export interface StoreFreshness {
  status: "open" | "closed" | "unclear";
  note: string;
  confidence: "high" | "low";
  checkedAt: string;
}

export const STORE_FRESHNESS: Record<string, StoreFreshness> = {
  "tom-james": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "norton-ditto": {
    "status": "unclear",
    "note": "",
    "confidence": "low",
    "checkedAt": "2026-08-31"
  },
  "hamilton-shirts": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "q-clothier": {
    "status": "open",
    "note": "Located at 2800 Kirby Dr, Ste B124; open daily with weekday hours 10am-6pm, Sat 11am-7pm, Sun 12pm-5pm.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "kuffs-houston": {
    "status": "unclear",
    "note": "",
    "confidence": "low",
    "checkedAt": "2026-08-31"
  },
  "lucho": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "bill-walker-clothier": {
    "status": "open",
    "note": "Located at 1737 Post Oak Blvd, Houston (Post Oak Plaza); active listing with regular hours and 2025 new-arrivals updates",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "blu-fine-menswear": {
    "status": "open",
    "note": "Private by-appointment studio at 2500 E T C Jester Blvd, Ste 205, Houston; call ahead to book a consultation.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "indochino-galleria": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "bzach-clothier": {
    "status": "open",
    "note": "Two Houston locations: 3733 Westheimer Rd Unit #3 and 6811 Southwest Fwy; custom & off-the-rack suits, book by appointment.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "festari-for-men": {
    "status": "open",
    "note": "Located at 1800 Post Oak Blvd Ste 6160 near the Galleria; family-owned custom/bespoke suit and tuxedo shop since 1993.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "m-penner": {
    "status": "unclear",
    "note": "",
    "confidence": "low",
    "checkedAt": "2026-08-31"
  },
  "neiman-marcus-galleria": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "saks-galleria": {
    "status": "open",
    "note": "Two-story Galleria flagship features Fifth Avenue Club, Virtual Appointments, and dining at 51fifteen",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "nordstrom-galleria": {
    "status": "open",
    "note": "Offers same-day delivery ($15 within 10 miles) and curbside pickup; open daily incl. Sun 12-7pm.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "zegna-houston": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "brioni-river-oaks": {
    "status": "open",
    "note": "Brioni opened its first Houston store in River Oaks District in 2024, next to Van Cleef & Arpels, offering bespoke tailoring and ready-to-wear.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "brunello-cucinelli-river-oaks": {
    "status": "open",
    "note": "Brunello Cucinelli plans a $1.8M expansion to 4,750+ sq ft at River Oaks District, construction expected April-Oct 2026.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "hermes-river-oaks": {
    "status": "open",
    "note": "Standalone two-story boutique at River Oaks District; open Mon-Sat 10am-6pm, closed Sundays.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "louis-vuitton-mens-galleria": {
    "status": "open",
    "note": "Offers on-site hot-stamping personalization service and a full fragrance counter; appointments can be booked online.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "the-black-tux-galleria": {
    "status": "open",
    "note": "Located at 5085 Westheimer Rd, The Galleria Level 2; open Mon–Sat 11:00AM–7:00PM.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "als-formal-wear": {
    "status": "open",
    "note": "Multiple Houston-area locations open; site currently running a free/discounted prom tuxedo rental promo.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "dxl-big-tall": {
    "status": "open",
    "note": "Curbside pickup available at this Westheimer location",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "sid-mashburn": {
    "status": "open",
    "note": "Store recently closed briefly for light renovations at the Westheimer/River Oaks Blvd location.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "suitsupply-river-oaks-district": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "rye-51": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "premium-goods": {
    "status": "open",
    "note": "Flash sale: $25 hats now until Sunday; recently launched Adidas Campus '00 collab (Jan 2026).",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "buck-mason": {
    "status": "open",
    "note": "Located at 906 Westheimer Rd, Montrose Collective; open Mon–Sat 11am–7pm, Sun 11am–6pm.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "marine-layer-rice-village": {
    "status": "unclear",
    "note": "",
    "confidence": "low",
    "checkedAt": "2026-08-31"
  },
  "manready-mercantile": {
    "status": "open",
    "note": "Open at 321 W 19th St; appeared at Houston Ballet Nutcracker Market 2025; site runs an online clearance sale (all discounted sales final).",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "lucchese": {
    "status": "open",
    "note": "Highland Village store hours: Mon-Sat 10am-7pm, Sun 12pm-6pm; offers custom boot design room.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "cavenders": {
    "status": "open",
    "note": "New Houston-area location opened July 2025 in Copperfield (6757 Hwy 6 N), a 23,500 sq ft former Party City space.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "tecovas-rice-village": {
    "status": "open",
    "note": "Tecovas is running a site-wide Cyber Week sale (Nov 26–Dec 2, 2025) with markdowns on boots and accessories.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "republic-boot-co": {
    "status": "open",
    "note": "Recently bought its Heights flagship building (E. 11th & Studewood) and opened a 2nd location, 'Republic Wine Castle,' in Johnson City, TX.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "the-hat-store": {
    "status": "open",
    "note": "5587 Richmond Ave; hours Tue–Fri 10–6, Sat 10–5, closed Sun–Mon; offers custom hat shaping, cleaning, boots & belts.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "pinto-ranch": {
    "status": "open",
    "note": "Also has a second Houston-area location at Bush Intercontinental Airport (IAH), Terminal C.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "allen-edmonds-houston": {
    "status": "open",
    "note": "",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "johnston-murphy-galleria": {
    "status": "open",
    "note": "Extra 20% off select styles online with code EXTRA20 at johnstonmurphy.com",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "qc-tailors": {
    "status": "open",
    "note": "3801 Kirby Dr, Suite 100, Upper Kirby; serving Houston since 1998, walk-ins welcome for alterations & custom tailoring.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "warby-parker-rice-village": {
    "status": "open",
    "note": "Open daily; hours Mon-Sat 10am-7pm, Sun 12pm-6pm at 2518 University Blvd, Rice Village.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "eye-elegance": {
    "status": "open",
    "note": "Eye Elegance is an optical boutique (not menswear), with two locations: 1703 Post Oak Blvd (Galleria) and 3939 Montrose Blvd.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "kuhl-linscomb": {
    "status": "open",
    "note": "Kuhl-Linscomb is running its annual Winter Sale with up to 20% off select items, including furniture",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  },
  "zadok-jewelers": {
    "status": "open",
    "note": "Holiday Trunk Show Series running through December 2025 featuring jewelry/watch brands like Vhernier, Pasquale Bruni, Ondyn, Nouvel Héritage.",
    "confidence": "high",
    "checkedAt": "2026-08-31"
  }
};
