// GENERATED by scripts/research-social.ts — do not hand-edit.
// Official public social profile links per store. Links only, by design:
// we point people at the source, we never copy its content.
export interface StoreSocial {
  instagram?: string;
  facebook?: string;
  active?: boolean;
}

export const STORE_SOCIAL: Record<string, StoreSocial> = {};
